### ISSUE TITLE
How get TPS?

### ISSUE THREAD

**Issue by Andrey228322** [thedudeguy/PHP-Minecraft-Rcon#13]
How get tps?

**Comment by thedudeguy** [comment]
I'm not quite sure what you mean, however the Issues section of this project is more for bugs related to the library code. As far as how to use the this library or how to make changes to the code, I can only recommend further studying the PHP language.

**Comment by metroyanno** [comment]
@thedudeguy, TPS - Ticks Per Second. It can be metered by plugin Essentials

**Comment by thedudeguy** [comment]
Thanks for clarifying. If there is a server command outputs that information, then you can execute that command via rcon  and check receive the output in the response.

```php
$rcon->sendCommand("tpscommand");
$output = $rcon->getResponse();
```
