### ISSUE TITLE
Fatal Error about memory

### ISSUE THREAD

**Issue by XanderCodes** [thedudeguy/PHP-Minecraft-Rcon#20]
Hello. My script connects to my server, but then i get this error:

Edit: Also i'm not actually running the RCON on a Minecraft server, but a Unturned one. Would this have something to do with it? Should i try it with a minecraft server?

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 1801678675 bytes) in C:\xampp\htdocs\PHP Testing\Rcon.php on line 207

Here is my index file (sorry if the scripting is bad, i'm sorta new to php): https://pastebin.com/VevZqCkH

And the send.php file: https://pastebin.com/nkAAPcZg
Thanks, Xander

**Comment by metroyanno** [comment]
The error itself speaks for itself. You may not have enough RAM

**Comment by XanderCodes** [comment]
For the server or the webhost?

**Comment by thedudeguy** [comment]
Increase the memory_limit setting in your php settings.

**Comment by XanderCodes** [comment]
I increased the Memory limit, but then it just wanted even more. I read up about the memory_limit setting, and found that if i set it to -1 it will take as much as it needs, but it still wanted more. The machine i'm running it on has 8gb, and i wouldn't think it would need that much??

EDIT: I fixed the memory issue, now the page just times out and my server console Says the client has disconnected. I have also changed my index file to this (without the button): https://pastebin.com/FHnkVwRN

**Comment by XanderCodes** [comment]
Hello??

**Comment by ricardoboss** [comment]
What happens if you turn off the time limit? (`set_time_limit(0);`)

**Comment by XanderCodes** [comment]
I'll try it

**Comment by XanderCodes** [comment]
This makes no difference, if i'm setting it right, i put it in my index.php under the variables for the server info??

**Comment by XanderCodes** [comment]
I did try my code with a MINECRAFT server, and it worked flawlessly, so can i simply not use this script with my Unturned server? I have tried other scripts, and none of them work with this gameserver, would it just be easier to establish a telnet-like connection over PHP?

**Comment by thedudeguy** [comment]
I haven't played Unturned so I don't know anything about it.  But I found some articles that stated it requires Rocket Mod in order to use RCON. Are you using that already?

**Comment by XanderCodes** [comment]
RocketMod is like Bukkit for Unturned, but RCON is one of its features. For now I have resorted to making a PHP button run a script on the physical server, but it would be really nice to have it done through RCON.

**Comment by thedudeguy** [comment]
Ok, thanks. Since the original topic, having to with memory, is resolved, I'm going to close this issue. I've created a new Issue specifically for Unturned, though, so that this can be further discussed.  
See #21
