### ISSUE TITLE
can only send "say hello world"

### ISSUE THREAD

**Issue by klyxmaster** [thedudeguy/PHP-Minecraft-Rcon#25]
can only send "say hello world" and "stop" all other commands just show:

Rcon connection from : /127.0.0.1

I am testing this on a vanilla server

**Comment by SomKen** [comment]
Can you share your code?

**Comment by klyxmaster** [comment]
thanks for the quick reply. yes
```

 $host = 'localhost'; /// Server host name or IP// sometimes will use 127.0.0.1
    $port = 25575;                      
    $password = 'rcon'; 
    $timeout = 3;                       
    
   // use Thedudeguy\Rcon;
    
    $rcon = new Rcon($host, $port, $password, $timeout);
    if(isset($_POST['send_command'])){
        if ($rcon->connect())
        {
          $rcon->sendCommand($_POST['command']);
        }
    }
   

```
Am NOT using composer, so had to comment out the "use" command

Its pretty much the same code as the example for testing. I did find it will do "time set day" as well (was going through all the commands in Minecraft

**Comment by klyxmaster** [comment]
Here is a screen shot when commands are sent but not recognized 
https://ibb.co/2NZMCHp

**Comment by klyxmaster** [comment]
user error :-(
I added 
`echo $rcon->getResponse();`

to my script, and saw that the responses are NOT displayed in the terminal but instead where ever you want it. Sorry about that - works perfect! thanks!
