### ISSUE TITLE
How can i read the answer of the command that i send? ^^

### ISSUE THREAD

**Issue by Henning-Klatt** [thedudeguy/PHP-Minecraft-Rcon#3]
When i send a command with your beautiful code, how can i get the answer of the command i send?
Its not really an Issue, but i cant find another way to contact you ;)

**Comment by thedudeguy** [comment]
The response is returned directly by the `send_command()` method. Additionally, it can be accessed using the `get_response()` method.

```php
$response = $rcon->send_command("say Hello World!");
echo $response;

//or
$rcon->send_command("say Hello World!");
echo $rcon->get_response();
```
