### ISSUE TITLE
Cant connect

### ISSUE THREAD

**Issue by ha1fdan** [thedudeguy/PHP-Minecraft-Rcon#30]
Warning: unpack(): Type V: not enough input, need 4, have 0 in C:\xampp\htdocs\MinecraftCP\rcon.php on line 198

Notice: Trying to access array offset on value of type bool in C:\xampp\htdocs\MinecraftCP\rcon.php on line 199

Warning: fread(): Length parameter must be greater than 0 in C:\xampp\htdocs\MinecraftCP\rcon.php on line 207

Warning: unpack(): Type V: not enough input, need 4, have 0 in C:\xampp\htdocs\MinecraftCP\rcon.php on line 208

Notice: Trying to access array offset on value of type bool in C:\xampp\htdocs\MinecraftCP\rcon.php on line 143

**Comment by SomKen** [comment]
Please share your code otherwise others cannot assist. :)

**Comment by ThePureCC** [comment]
@SomKen I'm getting this error as well. The errors are from the original code without any alterations.
