### ISSUE TITLE
Where i can get class 'Thedudeguy\Rcon'

### ISSUE THREAD

**Issue by t-constanta404** [thedudeguy/PHP-Minecraft-Rcon#32]
When i run a site, he have a:
### Fatal error: Class 'Thedudeguy\Rcon' not found in D:\OpenServer\domains\Timpixel-Main\donate_buy\PHP-Minecraft-Rcon-master\src\run.php on line 14

Where i can get this class?
Can u send me this class?

**Comment by ricardoboss** [comment]
How did you download this library?

**Comment by t-constanta404** [comment]
> How did you download this library?

In '<> Code' tab, 
Code > Download ZIP

**Comment by ricardoboss** [comment]
You need to unzip the downloaded file into your project root and then include the library using `include 'Rcon.php';`

**Comment by ricardoboss** [comment]
See https://www.php.net/manual/en/function.include.php for more info

**Comment by Timpixel2020** [comment]
> See https://www.php.net/manual/en/function.include.php for more info

I'm doing this, but how i can do, when my php version is report me: 'Сlass "Rcon.php" is old encoding'
I can't change PHP version! Can u decode code for PHP 7.0?

**Comment by t-constanta404** [comment]
> You need to unzip the downloaded file into your project root and then include the library using `include 'Rcon.php';`

Fatal error: Cannot declare class Thedudeguy\Rcon, because the name is already in use in D:\OpenServer\domains\Timpixel-Main\PHP-Minecraft-Rcon-master\src\Rcon.php on line 15

What i can do?

**Comment by ricardoboss** [comment]
Can you share your code? What have you tried?

**Comment by SomKen** [comment]
You need to share your code. At this point, I don't think anything is "private"...

**Comment by Timpixel2020** [comment]
**Rcon.php:**
<?php
/**
 * See https://developer.valvesoftware.com/wiki/Source_RCON_Protocol for
 * more information about Source RCON Packets
 *
 * PHP Version 7
 *
 * @copyright 2013-2017 Chris Churchwell
 * @author thedudeguy
 * @link https://github.com/thedudeguy/PHP-Minecraft-Rcon
 */

namespace Thedudeguy;

class Rcon
{
    private $host;
    private $port;
    private $password;
    private $timeout;

    private $socket;

    private $authorized = false;
    private $lastResponse = '';

    const PACKET_AUTHORIZE = 5;
    const PACKET_COMMAND = 6;

    const SERVERDATA_AUTH = 3;
    const SERVERDATA_AUTH_RESPONSE = 2;
    const SERVERDATA_EXECCOMMAND = 2;
    const SERVERDATA_RESPONSE_VALUE = 0;

    /**
     * Create a new instance of the Rcon class.
     *
     * @param string $host
     * @param integer $port
     * @param string $password
     * @param integer $timeout
     */
    public function __construct($host, $port, $password, $timeout)
    {
        $this->host = $host;
        $this->port = $port;
        $this->password = $password;
        $this->timeout = $timeout;
    }

    /**
     * Get the latest response from the server.
     *
     * @return string
     */
    public function getResponse()
    {
        return $this->lastResponse;
    }

    /**
     * Connect to a server.
     *
     * @return boolean
     */
    public function connect()
    {
        $this->socket = fsockopen($this->host, $this->port, $errno, $errstr, $this->timeout);

        if (!$this->socket) {
            $this->lastResponse = $errstr;
            return false;
        }

        //set timeout
        stream_set_timeout($this->socket, 3, 0);

        // check authorization
        return $this->authorize();
    }

    /**
     * Disconnect from server.
     *
     * @return void
     */
    public function disconnect()
    {
        if ($this->socket) {
                    fclose($this->socket);
        }
    }

    /**
     * True if socket is connected and authorized.
     *
     * @return boolean
     */
    public function isConnected()
    {
        return $this->authorized;
    }

    /**
     * Send a command to the connected server.
     *
     * @param string $command
     *
     * @return boolean|mixed
     */
    public function sendCommand($command)
    {
        if (!$this->isConnected()) {
                    return false;
        }

        // send command packet
        $this->writePacket(self::PACKET_COMMAND, self::SERVERDATA_EXECCOMMAND, $command);

        // get response
        $response_packet = $this->readPacket();
        if ($response_packet['id'] == self::PACKET_COMMAND) {
            if ($response_packet['type'] == self::SERVERDATA_RESPONSE_VALUE) {
                $this->lastResponse = $response_packet['body'];

                return $response_packet['body'];
            }
        }

        return false;
    }

    /**
     * Log into the server with the given credentials.
     *
     * @return boolean
     */
    private function authorize()
    {
        $this->writePacket(self::PACKET_AUTHORIZE, self::SERVERDATA_AUTH, $this->password);
        $response_packet = $this->readPacket();

        if ($response_packet['type'] == self::SERVERDATA_AUTH_RESPONSE) {
            if ($response_packet['id'] == self::PACKET_AUTHORIZE) {
                $this->authorized = true;

                return true;
            }
        }

        $this->disconnect();
        return false;
    }

    /**
     * Writes a packet to the socket stream.
     *
     * @param $packetId
     * @param $packetType
     * @param string $packetBody
     *
     * @return void
     */
    private function writePacket($packetId, $packetType, $packetBody)
    {
        /*
		Size			32-bit little-endian Signed Integer	 	Varies, see below.
		ID				32-bit little-endian Signed Integer		Varies, see below.
		Type	        32-bit little-endian Signed Integer		Varies, see below.
		Body		    Null-terminated ASCII String			Varies, see below.
		Empty String    Null-terminated ASCII String			0x00
		*/

        //create packet
        $packet = pack('VV', $packetId, $packetType);
        $packet = $packet.$packetBody."\x00";
        $packet = $packet."\x00";

        // get packet size.
        $packet_size = strlen($packet);

        // attach size to packet.
        $packet = pack('V', $packet_size).$packet;

        // write packet.
        fwrite($this->socket, $packet, strlen($packet));
    }

    /**
     * Read a packet from the socket stream.
     *
     * @return array
     */
    private function readPacket()
    {
        //get packet size.
        $size_data = fread($this->socket, 4);
        $size_pack = unpack('V1size', $size_data);
        $size = $size_pack['size'];

        // if size is > 4096, the response will be in multiple packets.
        // this needs to be address. get more info about multi-packet responses
        // from the RCON protocol specification at
        // https://developer.valvesoftware.com/wiki/Source_RCON_Protocol
        // currently, this script does not support multi-packet responses.

        $packet_data = fread($this->socket, $size);
        $packet_pack = unpack('V1id/V1type/a*body', $packet_data);

        return $packet_pack;
    }
}

**run.php:**
<?php
$host = '195.60.229.4' ; // Имя хоста сервера или IP 
$port = nope ;                      // Порт rcon прослушивает 
$password = 'nope' ; // настройка rcon.password установлена в server.properties 
$timeout = 3 ;                       // Как долго до тайм-аута.

require_once('Rcon.php');
include 'Rcon.php';

$rcon = new Rcon($host, $port, $password, $timeout);

if ($rcon->connect()){
  $rcon->sendCommand("say Привет Мир!");
}

**Comment by t-constanta404** [comment]
> Can you share your code? What have you tried?

http://timpixel-drive.ddns.net/uploades/Timpixel2020/PHP-Minecraft-Rcon-master.zip

**Comment by t-constanta404** [comment]
> You need to share your code. At this point, I don't think anything is "private"...

http://timpixel-drive.ddns.net/uploades/Timpixel2020/PHP-Minecraft-Rcon-master.zip

**Comment by ricardoboss** [comment]
```
require_once('Rcon.php');
include 'Rcon.php';
```

You only need to do one of these. The only difference is `include` will emit a warning if the file cannot be found and `require_once` will result in an error.

Next, you will need to either add:
```
use Thedudeguy\Rcon;
```

or:

```
$rcon = new Thedudeguy\Rcon($host, $port, $password, $timeout);
```

since the class exists within a namespace.

You can see an example in the README of this repository...

**Comment by t-constanta404** [comment]
I'll check, thx!

> ```
> require_once('Rcon.php');
> include 'Rcon.php';
> ```
> 
> You only need to do one of these. The only difference is `include` will emit a warning if the file cannot be found and `require_once` will result in an error.
> 
> Next, you will need to either add:
> 
> ```
> use Thedudeguy\Rcon;
> ```
> 
> or:
> 
> ```
> $rcon = new Thedudeguy\Rcon($host, $port, $password, $timeout);
> ```
> 
> since the class exists within a namespace.
> 
> You can see an example in the README of this repository...

I'll check, thx!

**Comment by t-constanta404** [comment]
> ```
> require_once('Rcon.php');
> include 'Rcon.php';
> ```
> 
> You only need to do one of these. The only difference is `include` will emit a warning if the file cannot be found and `require_once` will result in an error.
> 
> Next, you will need to either add:
> 
> ```
> use Thedudeguy\Rcon;
> ```
> 
> or:
> 
> ```
> $rcon = new Thedudeguy\Rcon($host, $port, $password, $timeout);
> ```
> 
> since the class exists within a namespace.
> 
> You can see an example in the README of this repository...

WOW!!! This work! Thx for help!

**Comment by ricardoboss** [comment]
Glad I could help! Would you mind closing this issue?

**Comment by t-constanta404** [comment]
> Glad I could help! Would you mind closing this issue?

ok
