### ISSUE TITLE
Not work :(

### ISSUE THREAD

**Issue by Arckazur** [thedudeguy/PHP-Minecraft-Rcon#5]
With this code : 
`
$host = " ***********:145 "; // Server host name or IP
    $port = "145";                         // Port rcon is listening on
    $password = " ****** ";   // rcon.password setting set in server.properties
    $timeout = 3;                          // How long to timeout.

    $rcon = new Rcon($host, $port, $password, $timeout);

      if ($rcon->connect())
      {
        $rcon->send_command("say Hello World!");
      }

    }
`

It not work it return : 
<b>Warning</b>:  unpack(): Type V: not enough input, need 4, have 0 in <b>/var/www/html/lib/rcon.php</b> on line <b>147</b><br />
<br />
<b>Warning</b>:  fread(): Length parameter must be greater than 0 in <b>/var/www/html/lib/rcon.php</b> on line <b>156</b><br />
<br />
<b>Warning</b>:  unpack(): Type V: not enough input, need 4, have 0 in <b>/var/www/html/lib/rcon.php</b> on line <b>157</b><br />

:(

**Comment by SomKen** [comment]
Remove :145 from the host.

**Comment by Daftpasteur** [comment]
Oh thanks, but I have an other question how I change the name of Rcon command ?

**Comment by thedudeguy** [comment]
I'm not sure I understand what you mean, but it doesn't sound like something related to this library in particular.

**Comment by thedudeguy** [comment]
I'm considering this issue resolved. Thanks for reporting. :)
