### ISSUE TITLE
Auto recomment

### ISSUE THREAD

**Issue by lluiscab** [thedudeguy/PHP-Minecraft-Rcon#6]
Is there any way to automatically reconnect if the conection timed out?  Some type of function for it or something like that?

**Comment by SomKen** [comment]
Without having access to a machine I can code from, this should be fairly easy to do.

Create a function that connects to rcon for you and return the rcon object back to the calling function.

When trying to read / write from the object, create a catch / try for attempting to use rcon.  If it fails, call the function that connects to rcon for you and attempt what you just did again.

Let me know if you need an example.  I'm no pro, but I've used this code for a while.

**Comment by lluiscab** [comment]
I think I know what you mean. Anyway, send me an example as I don't know exactly how to make the reconecting thing

**Comment by thedudeguy** [comment]
If the connection times out during the connect() method, it should return false, and any errors can be retrieved by immediately calling the get_response() method.

```php
$rcon = new Rcon($host, $port, $password, $timeout);

$success = $rcon->connect();

if ($success != true)
{
    $error = $rcon->get_response();
    
    // try to reconnect
}
```

Though to be honest, I haven't tested it much so it may not function as expected. If any exceptions are thrown, you'll need a try/catch clause.

I'm not quite sure if this is what you mean, though.

**Comment by lluiscab** [comment]
The idea is to use this class on a script that's constantly being executed, never ends, sometimes the server will be restarted and I want to be able to reconnect without restarting the script

**Comment by thedudeguy** [comment]
In that case you could do as SomKen suggested and and use try/catch when sending commands. Should the command fail to send for any reason, such as a connection that has been closed the error should be thrown in which you can proceed accordingly.

```php
try {
    $rcon->send_command("say Hello World!");
} catch (Exception $e) {
    echo 'Caught exception: ',  $e->getMessage(), "\n";
    
    // todo: run logic to re-open the connection.
}
```

http://php.net/manual/en/language.exceptions.php
